-- local status, prettier = pcall(require, "prettier")
-- if not status then
--   return
-- end

-- -- local group = vim.api.nvim_create_augroup("lsp_format_on_save", { clear = false })
-- -- -- local event = "BufWritePre" -- or "BufWritePost"
-- -- local event = "BufWritePost"
-- -- local async = event == "BufWritePost"

-- prettier.setup({
--   -- bin = "prettierd",
--   bin = "prettierd",
--   filetypes = {
--     "*",
--     -- "css",
--     -- "graphql",
--     -- "html",
--     -- "javascript",
--     -- "javascriptreact",
--     -- "json",
--     -- "less",
--     -- "markdown",
--     -- "scss",
--     -- "typescript",
--     -- "yaml",
--   },
--   -- cli_options = {
--   -- 	arrow_parens = "always",
--   -- 	bracket_spacing = true,
--   -- 	bracket_same_line = false,
--   -- 	embedded_language_formatting = "auto",
--   -- 	end_of_line = "lf",
--   -- 	html_whitespace_sensitivity = "css",
--   -- 	-- jsx_bracket_same_line = false,
--   -- 	jsx_single_quote = false,
--   -- 	print_width = 80,
--   -- 	prose_wrap = "preserve",
--   -- 	quote_props = "as-needed",
--   -- 	semi = false,
--   -- 	single_attribute_per_line = false,
--   -- 	single_quote = true,
--   -- 	tab_width = 2,
--   -- 	trailing_comma = "es5",
--   -- 	use_tabs = false,
--   -- 	vue_indent_script_and_style = false,
--   -- },
--   -- on_attach = function(client, bufnr)
--   -- 	-- format on save
--   -- 	vim.api.nvim_clear_autocmds({ buffer = bufnr, group = group })
--   -- 	vim.api.nvim_create_autocmd(event, {
--   -- 		buffer = bufnr,
--   -- 		group = group,
--   -- 		callback = function()
--   -- 			vim.lsp.buf.format({ bufnr = bufnr, async = async })
--   -- 		end,
--   -- 		desc = "[lsp] format on save",
--   -- 	})
--   -- end,
-- })
